### ISSUE TITLE
Limit metadata.name field to 15 characters

### ISSUE THREAD

**Issue by scottd018** [rh-mobb/ocm-operator#3]
To account for the node pool naming limitation, we also need to limit our metadata.name field to 15 characters.  Typically, this is done via CRD CEL in the following manner:

```go
//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
//+kubebuilder:validation:XValidation:message="metadata.name limited to 15 characters",rule=(self.metadata.name.size() <= 15)

// MachinePool is the Schema for the machinepools API.
type MachinePool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MachinePoolSpec   `json:"spec,omitempty"`
	Status MachinePoolStatus `json:"status,omitempty"`
}
```

However, kubebuilder does not seem to patch the metadata field.

Need to create a custom Kustomize patch in the config/crd/patches directory to inject the following to the crd:

```yaml
          metadata:
            type: object
            x-kubernetes-validations:
            - message: metadata.name limited to 15 characters
              rule: (self.metadata.name.size() <= 15)
```
